### ISSUE TITLE
Syntax Highlighting for Table Delimiters

### ISSUE THREAD

**Issue by polyglot-jones** [tajmone/ST3-Asciidoctor#9]
There is not yet any syntax highlighting for table delimiters. I'll work on it.

**Comment by polyglot-jones** [comment]
I've been convinced that this is too difficult and not worth the effort.

**Comment by tajmone** [comment]
> I've been convinced that this is too difficult and not worth the effort.

I've been doing some local tests with this. I think its doable, but also that right now the syntax is too messy to introduce this, and that it would be better to postpone it to a time where the syntax contexts are disentangled.
